services:
  - type: web
    name: lifetube-web
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://lifetube-server-production.up.railway.app/api
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
